language: php

php:
  - '5.3'
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'

before_script:
  - composer update
  - mkdir -p vendor/php-platform/testconfig123456

script:
  - ./vendor/bin/phpunit -c phpunit.xml 